# Generated by Django 2.1 on 2018-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='username',
            field=models.CharField(default='C143027', help_text='Please Enter Your Student ID', max_length=7, unique=True),
        ),
    ]
